import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";
import '@fortawesome/fontawesome-svg-core/styles.css';
import { GuestStatsProvider } from "./hooks/useGuestStats";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Typeracer - Race Your Typing Skills",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <GuestStatsProvider>
          <Header />
          <main className="pt-16 min-h-screen">{/* Décalage pour le header fixe */}
            {children}
          </main>
          <Footer />
        </GuestStatsProvider>
      </body>
    </html>
  );
}
